[build]
  publish = "public"
  functions = "netlify/functions"

[functions."update-scores"]
  schedule = "0 23 * * *"

[[redirects]]
  from = "/api/create-room"
  to = "/.netlify/functions/create-room"
  status = 200

[[redirects]]
  from = "/api/get-room"
  to = "/.netlify/functions/get-room"
  status = 200

[[redirects]]
  from = "/api/update-scores"
  to = "/.netlify/functions/update-scores"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
